# ---------------------------
# Instrument List and Dropdown Setup
# ---------------------------

instrument_list = [
    {"name": "Acoustic Grand Piano", "bank": 0, "program": 0},
    {"name": "Bright Acoustic Piano", "bank": 0, "program": 1},
    {"name": "Electric Grand Piano", "bank": 0, "program": 2},
    {"name": "Honky-tonk Piano", "bank": 0, "program": 3},
    {"name": "Electric Piano 1", "bank": 0, "program": 4},
    {"name": "Electric Piano 2", "bank": 0, "program": 5},
    {"name": "Harpsichord", "bank": 0, "program": 6},
    {"name": "Clavinet", "bank": 0, "program": 7},
    {"name": "Celesta", "bank": 0, "program": 8},
    {"name": "Glockenspiel", "bank": 0, "program": 9},
    {"name": "Music Box", "bank": 0, "program": 10},
    {"name": "Vibraphone", "bank": 0, "program": 11},
    {"name": "Marimba", "bank": 0, "program": 12},
    {"name": "Xylophone", "bank": 0, "program": 13},
    {"name": "Tubular Bells", "bank": 0, "program": 14},
    {"name": "Dulcimer", "bank": 0, "program": 15},
    {"name": "Drawbar Organ", "bank": 0, "program": 16},
    {"name": "Percussive Organ", "bank": 0, "program": 17},
    {"name": "Rock Organ", "bank": 0, "program": 18},
    {"name": "Church Organ", "bank": 0, "program": 19},
    {"name": "Reed Organ", "bank": 0, "program": 20},
    {"name": "Accordion", "bank": 0, "program": 21},
    {"name": "Harmonica", "bank": 0, "program": 22},
    {"name": "Tango Accordion", "bank": 0, "program": 23},
    {"name": "Acoustic Guitar (nylon)", "bank": 0, "program": 24},
    {"name": "Acoustic Guitar (steel)", "bank": 0, "program": 25},
    {"name": "Electric Guitar (jazz)", "bank": 0, "program": 26},
    {"name": "Electric Guitar (clean)", "bank": 0, "program": 27},
    {"name": "Electric Guitar (muted)", "bank": 0, "program": 28},
    {"name": "Overdriven Guitar", "bank": 0, "program": 29},
    {"name": "Distortion Guitar", "bank": 0, "program": 30},
    {"name": "Guitar harmonics", "bank": 0, "program": 31},
    {"name": "Acoustic Bass", "bank": 0, "program": 32},
    {"name": "Electric Bass (finger)", "bank": 0, "program": 33},
    {"name": "Electric Bass (pick)", "bank": 0, "program": 34},
    {"name": "Fretless Bass", "bank": 0, "program": 35},
    {"name": "Slap Bass 1", "bank": 0, "program": 36},
    {"name": "Slap Bass 2", "bank": 0, "program": 37},
    {"name": "Synth Bass 1", "bank": 0, "program": 38},
    {"name": "Synth Bass 2", "bank": 0, "program": 39},
    {"name": "Violin", "bank": 0, "program": 40},
    {"name": "Viola", "bank": 0, "program": 41},
    {"name": "Cello", "bank": 0, "program": 42},
    {"name": "Contrabass", "bank": 0, "program": 43},
    {"name": "Tremolo Strings", "bank": 0, "program": 44},
    {"name": "Pizzicato Strings", "bank": 0, "program": 45},
    {"name": "Orchestral Harp", "bank": 0, "program": 46},
    {"name": "Timpani", "bank": 0, "program": 47},
    {"name": "String Ensemble 1", "bank": 0, "program": 48},
    {"name": "String Ensemble 2", "bank": 0, "program": 49},
    {"name": "SynthStrings 1", "bank": 0, "program": 50},
    {"name": "SynthStrings 2", "bank": 0, "program": 51},
    {"name": "Choir Aahs", "bank": 0, "program": 52},
    {"name": "Voice Oohs", "bank": 0, "program": 53},
    {"name": "Synth Voice", "bank": 0, "program": 54},
    {"name": "Orchestra Hit", "bank": 0, "program": 55},
    {"name": "Trumpet", "bank": 0, "program": 56},
    {"name": "Trombone", "bank": 0, "program": 57},
    {"name": "Tuba", "bank": 0, "program": 58},
    {"name": "Muted Trumpet", "bank": 0, "program": 59},
    {"name": "French Horn", "bank": 0, "program": 60},
    {"name": "Brass Section", "bank": 0, "program": 61},
    {"name": "SynthBrass 1", "bank": 0, "program": 62},
    {"name": "SynthBrass 2", "bank": 0, "program": 63},
    {"name": "Soprano Sax", "bank": 0, "program": 64},
    {"name": "Alto Sax", "bank": 0, "program": 65},
    {"name": "Tenor Sax", "bank": 0, "program": 66},
    {"name": "Baritone Sax", "bank": 0, "program": 67},
    {"name": "Oboe", "bank": 0, "program": 68},
    {"name": "English Horn", "bank": 0, "program": 69},
    {"name": "Bassoon", "bank": 0, "program": 70},
    {"name": "Clarinet", "bank": 0, "program": 71},
    {"name": "Piccolo", "bank": 0, "program": 72},
    {"name": "Flute", "bank": 0, "program": 73},
    {"name": "Recorder", "bank": 0, "program": 74},
    {"name": "Pan Flute", "bank": 0, "program": 75},
    {"name": "Blown Bottle", "bank": 0, "program": 76},
    {"name": "Shakuhachi", "bank": 0, "program": 77},
    {"name": "Whistle", "bank": 0, "program": 78},
    {"name": "Ocarina", "bank": 0, "program": 79},
    {"name": "Lead 1 (square)", "bank": 0, "program": 80},
    {"name": "Lead 2 (sawtooth)", "bank": 0, "program": 81},
    {"name": "Lead 3 (calliope)", "bank": 0, "program": 82},
    {"name": "Lead 4 (chiff)", "bank": 0, "program": 83},
    {"name": "Lead 5 (charang)", "bank": 0, "program": 84},
    {"name": "Lead 6 (voice)", "bank": 0, "program": 85},
    {"name": "Lead 7 (fifths)", "bank": 0, "program": 86},
    {"name": "Lead 8 (bass + lead)", "bank": 0, "program": 87},
    {"name": "Pad 1 (new age)", "bank": 0, "program": 88},
    {"name": "Pad 2 (warm)", "bank": 0, "program": 89},
    {"name": "Pad 3 (polysynth)", "bank": 0, "program": 90},
    {"name": "Pad 4 (choir)", "bank": 0, "program": 91},
    {"name": "Pad 5 (bowed)", "bank": 0, "program": 92},
    {"name": "Pad 6 (metallic)", "bank": 0, "program": 93},
    {"name": "Pad 7 (halo)", "bank": 0, "program": 94},
    {"name": "Pad 8 (sweep)", "bank": 0, "program": 95},
    {"name": "FX 1 (rain)", "bank": 0, "program": 96},
    {"name": "FX 2 (soundtrack)", "bank": 0, "program": 97},
    {"name": "FX 3 (crystal)", "bank": 0, "program": 98},
    {"name": "FX 4 (atmosphere)", "bank": 0, "program": 99},
    {"name": "FX 5 (brightness)", "bank": 0, "program": 100},
    {"name": "FX 6 (goblins)", "bank": 0, "program": 101},
    {"name": "FX 7 (echoes)", "bank": 0, "program": 102},
    {"name": "FX 8 (sci-fi)", "bank": 0, "program": 103},
    {"name": "Sitar", "bank": 0, "program": 104},
    {"name": "Banjo", "bank": 0, "program": 105},
    {"name": "Shamisen", "bank": 0, "program": 106},
    {"name": "Koto", "bank": 0, "program": 107},
    {"name": "Kalimba", "bank": 0, "program": 108},
    {"name": "Bag pipe", "bank": 0, "program": 109},
    {"name": "Fiddle", "bank": 0, "program": 110},
    {"name": "Shanai", "bank": 0, "program": 111},
    {"name": "Tinkle Bell", "bank": 0, "program": 112},
    {"name": "Agogo", "bank": 0, "program": 113},
    {"name": "Steel Drums", "bank": 0, "program": 114},
    {"name": "Woodblock", "bank": 0, "program": 115},
    {"name": "Taiko Drum", "bank": 0, "program": 116},
    {"name": "Melodic Tom", "bank": 0, "program": 117},
    {"name": "Synth Drum", "bank": 0, "program": 118},
    {"name": "Reverse Cymbal", "bank": 0, "program": 119},
    {"name": "Guitar Fret Noise", "bank": 0, "program": 120},
    {"name": "Breath Noise", "bank": 0, "program": 121},
    {"name": "Seashore", "bank": 0, "program": 122},
    {"name": "Bird Tweet", "bank": 0, "program": 123},
    {"name": "Telephone Ring", "bank": 0, "program": 124},
    {"name": "Helicopter", "bank": 0, "program": 125},
    {"name": "Applause", "bank": 0, "program": 126},
    {"name": "Gunshot", "bank": 0, "program": 127},
]